### ISSUE TITLE
Boolean validation failed

### ISSUE THREAD

**Issue by hidogcat** [intridea/grape#1002]
Hi there,
There is a defect about validation, for example:
WHEN
params: some_name do
   xxx
   requires :some_symbol, type: Grape::API::Boolean, allow_blank: false
   xxx
end
THEN 
send the request with some_symbol = false 
GOT  
a bad request with "error": "some_name[some_symbol] is empty"

This happened when allow_blank is false

Best regards,
Zhijia

**Comment by dblock** [comment]
Please try to write a spec for this?

**Comment by mfunaro** [comment]
I've noticed this too. I believe it's because the allow_blank validator is using the rails present? method which will treat false as not present and therefore fail the validation.

**Comment by dm1try** [comment]
Fixed in https://github.com/intridea/grape/pull/1012
