### ISSUE TITLE
No longer can rescue SecurityError exceptions with rescue_from

### ISSUE THREAD

**Issue by urkle** [intridea/grape#1006]
In grape 0.4.1 we could do this.
```
rescue_from SecurityError do
end
```
However since 0.6.1 this is no longer possible as the error middleware is only catching StandardError instead of Exception

This change was made in this commit f038ed5457cef80

Is this an intended change or just accidental from the Rubocop addition?

**Comment by dblock** [comment]
I think this was intended, but maybe we should reconsider? Why would something be throwing SecurityError inside a request?

**Comment by urkle** [comment]
I'm actually throwing it in certain conditions in some API methods to denite that "the user tried to do something they were supposed to"..   a specific example was in a client API endpoint we deprecated value for one of the options and threw the security error if any "old" client attempted to use that functionality so we could track it.

Right now we are in the process of upgrading our application from Ruby 1.9.3 -> 2.1.5 and with that came the need to upgrade to the latest grape.  for now we've simply reworked that code (and similar) to use a custom exception instead.

**Comment by dblock** [comment]
I think that Grape is doing the right thing and should not be rescuing and potentially swallowing SecurityError, it's something that is purposely not deriving from StandardError, it's raised when attempting a potential unsafe operation, typically when the $SAFE level is raised above 0. 

You're doing the right thing reworking the code. A real SecurityError thrown should be handled differently from a "user doesn't have access".

I'll close this.
