### ISSUE TITLE
Array-type Parameter Validation?

### ISSUE THREAD

**Issue by tvaillancourt** [intridea/grape#1013]
Hey guys,

Just to start: this is not an issue but more of a question or possible feature-request. Also, thanks for making Grape, really enjoying it!

I've built an API in Grape that accepts JSON in the body of PUT/POST requests and my API spec requires the body to be an array-type list of documents/hashes to be updated, each document having the exact same required fields.

Because my API spec requires the PUT/POST body to be an array of changes, (so far) I've been unable to use the built-in Parameter Validation in Grape, as it seems to be designed to expect hashes, not arrays of hashes. I hypothetically could restructure my API spec to fit into Grape's expectation of hashes, but that is unfortunately not possible for various non-technical reasons.

Is there any way for me to use the builtin Parameter Validation in Grape on an array of hashes/documents instead of a single hash, or would this be a new feature? Again, each hash in the array requires the same fields to exist, so I'd essentially need Grape to "loop" over the array and otherwise do the same validation.

Any thoughts are appreciated!

Tim

**Comment by mfunaro** [comment]
Not knowing what the code looks like, why not structure the params so that it requires an Array type which has nested hashes?

Something like this
```ruby
params do
  requires :users, type: Array do
    requires :user, type: Hash do
      # params here
    end
  end
end
```

**Comment by dblock** [comment]
Grape allows for arrays of hashes, via `type: Array` for a `group`, I think. If you can't get it to work, bring this up on the [mailing list](http://groups.google.com/group/ruby-grape)?

**Comment by tvaillancourt** [comment]
Fantastic, thanks dblock. I will try and discuss on the mailinglist, I didn't realize there was one.
