### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by guizmaii** [intridea/grape#1019]
Hi,

As explained here : https://github.com/egonSchiele/contracts.ruby/pull/154, I use the ```Contracts``` gem (https://github.com/egonSchiele/contracts.ruby/) in one of my Rails project.

It works fine until I put ```grape``` in my Gemfile.

When I add ```grape```, I have name collisions between one of my rails model named ```Support``` and one of the ```Contract``` module named ```Contracts::Support```.

Do you have an idea where it could come from and how to avoid this problem ?

KR,
Jules

**Comment by dblock** [comment]
I am confused to how grape would introduce this problem by just being included, maybe you can try and produce a small repro?

**Comment by dm1try** [comment]
Any news? Seems it's not related to `grape` at all.

**Comment by guizmaii** [comment]
Effectively ! I close the issue. Sorry for that.
