### ISSUE TITLE
Nested routes causing Rails - Unable to autoload constant error

### ISSUE THREAD

**Issue by zulkamal** [intridea/grape#1021]
I'm having an issue with setting up this route in a rails mounted api: `/api/v1/customers/:customer_id/stores/:store_id/products`

The api is defined in a customers.rb:

```ruby
module API
  module V1
    class Customers < Grape::API
      version 'v1'
      format :json

      # /cutomers
      namespace :customers do
        desc "Creates a new customer"
        params do
            requires :name, type: "String", desc: "Customer Name"
            requires :contact, type: "String", desc: "Contact Person"
        end
        post do
          # do something
        end

        # /:id
        route_param :customer_id do
          get do
            {}
          end

          route_param :store_id do
            desc "GET"
            get do
              {}
            end

            get 'products' do
              {}
            end
          end
        end
      end
    end
  end

  module Entities
    class Customer < Grape::Entity
      expose :name
      expose :contact
    end

    class Store < Grape::Entity
      expose :id
      expose :name
    end
  end
end
```

The rest of the route works perfectly:

- `/api/v1/customers/:customer_id` - ok
- `/api/v1/customers/:customer_id/stores/:store_id` - ok
- `/api/v1/customers/:customer_id/stores/:store_id/products` - fails

The error is odd since the code is already running in customers.rb: 

```ruby
Unable to autoload constant Api::V1::Customers, expected /localpath/src/app/api/api/v1/customers.rb to define it
```

I'm guessing this could be a bug?

**Comment by dblock** [comment]
Notice that you have a double `api` in the error - you bneed to have `app` in your loading path, not `app/api` and I think it will work. I'll close this since it's not a Grape issue, but feel free to bring this up on the mailing list if you still can't figure it out.
