### ISSUE TITLE
Rack apps should return array

### ISSUE THREAD

**Issue by lasseebert** [intridea/grape#1041]
In this commit released with 0.12.0: 129ad6ef8d22579425f5b6ab655cd0c476d0bc76, the formatter middleware now returns a `Rack::Response` and not an array.

From what I understand, this breaks Rack's conventions (and broke the middleware in my app).
Also, the docs for `Rack::Response` clearly states that an app should return `Rack::Response#finish` (aliased to `#to_a`).

Any reason this has been done?
If not, I will be happy to provide a pull request that reverses the commit ;)

**Comment by dblock** [comment]
This is in UPGRADING, and see https://github.com/intridea/grape/pull/1029.

Rack spec (from what I remember after reading a lot of it :) just says you're supposed to return a Rack::Response or a "file-like object". With the change you describe above we are able to return a file stream. I couldn't find a single example where returning a Rack::Response itself would be an issue.

Are you seeing something broken or are you just worried about the convention?

**Comment by lasseebert** [comment]
Thanks for the answer ;)
I didn't realize this was for streaming (and I didn't notice the `UPGRADING` untill now)

This broke a custom rack middleware in my app, because in some scenarios it will be just before the `Formatter` middleware.

If I need to make changes to the response before returning from my middleware, I must now first check if it is an `Array` or a `Rack::Response` (The middleware is used in many different places).

If this is expected behavior, issue can be closed ;)

**Comment by dblock** [comment]
Yes, since UPGRADING documents this pretty thoroughly I think we're good. It's also easier to work with a `Rack::Response` in another middleware, you might want to consider adjusting all your code to that.

**Comment by wagenet** [comment]
@dblock sorry to reopen an old issue here. From what I can tell, the Rack API docs do imply that you should not return the Rack::Response itself from the `app.call`:

> Your application's call should end returning Response#finish.

via http://www.rubydoc.info/github/rack/rack/Rack/Response

**Comment by wagenet** [comment]
Also:

> A Rack application is a Ruby object (not a class) that responds to call. It takes exactly one argument, the environment and returns an Array of exactly three values: The status, the headers, and the body.

http://www.rubydoc.info/github/rack/rack/master/file/SPEC

**Comment by dblock** [comment]
I just don't read it the same way I suppose. If we undo this the whole streaming thing doesn't work at all, no?

**Comment by wagenet** [comment]
@dblock, I haven't read the code, but wouldn't you do streaming by having the 3 value of the array be a special object that responds to each? http://www.rubydoc.info/github/rack/rack/file/SPEC#The_Body

**Comment by dblock** [comment]
From what I understand that doesn't work because of how Rack treats this, but I could be totally wrong. Maybe @dan-corneanu can help us here?

**Comment by wagenet** [comment]
@dblock yeah, I'm just reading the spec, might be things I'm missing. It looks like Rails is just doing something with `Rack::Chunked::Body`: https://github.com/rails/rails/blob/b6760d8f14af6b00250395f2c830b89e43621860/actionpack/lib/action_controller/metal/streaming.rb

**Comment by wagenet** [comment]
@dblock ran across this again and I still believe that Grape's behavior here is incorrect.

**Comment by wagenet** [comment]
I'm virtually certain that the correct approach for streaming is to return a body (the third array element in the response) that handles the streaming. The response from `call` should always be a simple array.

**Comment by dblock** [comment]
I am not sure what to do with this, I think you should raise a PR and we can look at the change?

**Comment by wagenet** [comment]
@dblock With some recent changes to Rack it seems like this may not work correctly anymore as implicit destructuring is no longer supported: https://github.com/rack/rack/commit/72959ebc2f300f3b2ccb7ae2aae9f199e611dfb6#diff-10b933d2c1fdc82ceecade456c64e1c2

**Comment by lamdn-ponos** [comment]
@dblock I encountered the same error when using Rack v2.x with Grape > v1.2.5.

Since `Grape::Endpoint` uses both `Rack::Head` and `Grape::Middleware::Formatter` in the middleware stack, the value returned after `Grape::Middleware::Formatter` is a `Rack::Response`. This response is then passed to `Rack::Head` at [head.rb#L12](https://github.com/rack/rack/blob/2.0.0/lib/rack/head.rb#L12).

After these middlewares run, the final return value becomes an array like this:

```
[<Rack::Response>, nil, nil]
```

This cause an error at [router.rb#L137](https://github.com/ruby-grape/grape/blob/v0.16.0/lib/grape/router.rb#L137), where the `response[1]` is nil.

**Comment by dblock** [comment]
@lamdn-ponos Try writing a (failing) integration test?
