### ISSUE TITLE
Make Grape::Exceptions full_messages public

### ISSUE THREAD

**Issue by romanlehnert** [intridea/grape#1058]
```Grape::Exceptions::ValidationErrors#message``` currently joins the error messages together. Example:
```ruby
"id is missing, name is missing"
```

However, when building custom error responses, that handle each single validation error separately, ```Grape::Exceptions::ValidationErrors#full_messages``` is extremely useful:
```ruby
["id is missing", "name is missing"]
```

But this method is private. So my questions are 
* What do you think about making this method public? 
* Or is there a better way to access the single validation error messages?

Thanks!

**Comment by dblock** [comment]
I don't see a problem with making this method public. Write a spec for it and make a PR.

**Comment by romanlehnert** [comment]
I'll do that. thanks.

**Comment by romanlehnert** [comment]
Closing, since #1064 is merged.
