### ISSUE TITLE
How do you do semantic versioning with Grape's path strategy?

### ISSUE THREAD

**Issue by mcoms** [intridea/grape#1075]
I have a production Grape project which uses the `path` versioning strategy. Right now, everything is `v1` using:

```ruby
# /api/v1/users
class API::V1::Users::Root < Grape::API
  version 'v1', using: :path, vendor: 'api'
  format :json
  mount API::V1::Users::CurrentUser
  # ...
end
```

I'd like to continue using path-based versioning, and add a single new route to this API and call it `v1.1`. I'd also like to have requests cascade down to the `v1` implementation if they are not reimplemented in `v1.1`.

Is this possible?  Thanks!

**Comment by dblock** [comment]
I think you're looking for http://code.dblock.org/2013/07/19/evolving-apis-using-grape-api-versioning.html. 

Please use the mailing list for questions!
