### ISSUE TITLE
Extra routes created for unspecified methods

### ISSUE THREAD

**Issue by wagenet** [intridea/grape#1080]
Given the following code:

```rb
module Acme
  class Post < Grape::API
    desc 'Creates a spline that can be reticulated.'
    resource :spline do
      post do
        { reticulated: params[:reticulated] }
      end
    end
  end
end
```

(via https://github.com/dblock/grape-on-rails/blob/master/app/api/acme/post.rb)

Not only do I get a `POST /spline` route, I also get a shared `GET PUT DELETE PATCH HEAD /spline` route that just returns an empty string. 

My expectation is that only the `POST` route would be created. I'm not sure where the others are coming from. It also seems to be inconsistent when the additional route is created. I've had other similar circumstances where that route did not exist.

**Comment by dblock** [comment]
That wouldn't be expected behavior for sure. Those routes should be returning 406s. Care to write a test or a demo of it?

**Comment by wagenet** [comment]
This can be demoed with the standard grape-on-rails repo at https://github.com/dblock/grape-on-rails. 

Both of these return an empty string but I would expect a failure:

`curl http://localhost:3000/api/spline`
`curl http://localhost:3000/api/spline -X PUT -d 'reticulated=foo'`

**Comment by dblock** [comment]
It's returning a 405 in my case (and yes, it does return an empty body).

```
~/source/grape-on-rails/dblock (master)$ curl http://localhost:3000/api/spline  -v
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 3000 (#0)
> GET /api/spline HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:3000
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed 
< Allow: OPTIONS, POST
< Content-Type: application/json
< Content-Length: 2
< Cache-Control: no-cache
< X-Request-Id: 30932d94-78dc-4be3-9e9d-e86b3d38934a
< X-Runtime: 0.001793
* Server WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08) is not blacklisted
< Server: WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)
< Date: Fri, 31 Jul 2015 19:18:05 GMT
< Connection: Keep-Alive
```

Why Chrome renders the page instead of producing an error, I am not sure. 

Is this not what you're seeing?

**Comment by wagenet** [comment]
Ah, it does indeed return a 405. I was also expecting to see a "No route matches" error from Rails as you do with other invalid URLs, like `/api/ping/foo`.

**Comment by dblock** [comment]
No route matches would be a 404, which is incorrect. When you are invoking a well known route with the wrong method you get a different error than if the route doesn't exist. That's HTTP RFC, but don't ask me for a quote :) So this is explicitly defined here: https://github.com/intridea/grape/blob/b474f5e40f8c06490fba0790e57e438c630ec23f/lib/grape/api.rb#L177. 

I am going to close this, reopen if you disagree. Thanks for bringing this up!

**Comment by wagenet** [comment]
Ok, that makes sense now.
