### ISSUE TITLE
Build named path using url helper

### ISSUE THREAD

**Issue by kinko912000** [intridea/grape#863]
This issue was as follows

http://stackoverflow.com/questions/27578341/how-to-build-named-helper-using-grape-on-rails/27585384

**Comment by reprah** [comment]
From the research I've done regarding how named routes and route sets are generated, they're pretty closely involved with Rails::Railtie and I'm unsure how a plain Rack app would be able to have this feature. @dblock did you have any broad ideas for how this can be implemented that I can look into?

**Comment by dblock** [comment]
I think a route should figure out what its helper method is [here](https://github.com/intridea/grape/blob/master/lib/grape/endpoint.rb#L153) and then a `method_missing` implementation would emit a method when something wants `..._path` by looking up a route that matches in `.routes`.

**Comment by reprah** [comment]
Ok, I was approaching this thinking "how can I get a Grape API's routes to end up in the url_helpers module when `mount` is called in the routes file?", since that's what seems to happen for Rails engines and this seems like an analogous situation.

Were you thinking the method_missing method that finds tthe right Grape route should be defined in a separate module that Grape provides (and a user would have to include)? Or something else entirely?

**Comment by dblock** [comment]
Yes to the module, but ultimately Endpoint would extend it.

**Comment by reprah** [comment]
@dblock Hi, I've got a working implementation for path helper methods and would like your feedback about the overall idea before I keep moving forward.

I want to support helper methods for both simple cases (api_v2_statuses_path returns '/api/v2/statuses') and more complicated ones (e.g., users_path(id: 2, format: 'xml') would return '/users/2.xml') that need a programmer's input via arguments. Here's the general flow:

1.) There's a UrlHelpers module. Its method_missing looks up a Grape::Route that responds to the missing method, and sends the method/arguments to that route

2.) When a Grape::Route is initialized, it determines its helper name by looking at route_path and filling in any dynamic segments  with values in @options. For example 'api/:version/tasks' becomes 'api_v1_tasks_path'

3.) Grape::Route then defines that helper method on itself. This method returns the path. The method should take arguments so the programmer can pass in things like an ID to generate the correct path

I thought this was the most straightforward thing to do - the UrlHelpers module just finds the matching route like you described, and Grape::Route does the hard work of figuring out the method name and generating a method that returns the correct path.

**Comment by dblock** [comment]
That sounds good, and that said you cannot have any ambiguity in these, ie. users_path either takes (aka requires) parameters or doesn't (cause it either has a dynamic portion or it doesn't).

**Comment by reprah** [comment]
Figuring out how to resolve that ambiguity is what I'm doing right now. There are two options I can see:

1.) Any required dynamic portion becomes part of the method name (e.g., '/users/:id/' becomes users_id_path)

2.) The arguments passed into the method determine which route is invoked (e.g., users_path() would use the route with the path '/users', and users_path(id: 1) would use the route with the path '/users/:id')

Any ideas I may have overlooked?

**Comment by dblock** [comment]
Definitely 2).

**Comment by dblock** [comment]
A new gem, https://github.com/reprah/grape-route-helpers, accomplishes this.
