### ISSUE TITLE
How do you unit test a POST with a JSON body?

### ISSUE THREAD

**Issue by jcavalieri** [intridea/grape#884]
I'm trying to unit test a post with a json body and I'm just getting a 404 response.

E.g.
```
          params = {
              'whatever' => 'whatever'
            }

          request_headers = {
              'Accept' => 'application/json',
              'Content-Type' => 'application/json'
          }

          post "/v1/order-status/#{order_number}", params.to_json, request_headers
```
If I look at the response in a debugger it is a 404.

However, testing "GET" works and POSTing with curl works.

Thanks,
John

**Comment by dblock** [comment]
This should have worked, can you write a full spec in Grape like this, please? I would put it into https://github.com/intridea/grape/tree/master/spec/grape/integration.

**Comment by jcavalieri** [comment]
Thanks for the alternative. I'll give it a try when I have chance.

**Comment by dm1try** [comment]
Do you use `Rack::Test`request helpers or `ActionDispatch::Integration::RequestHelpers` helpers?
Their third param is different. 

see [rack test #post](https://github.com/brynary/rack-test/blob/acdbee66fc765f15c2d3a1a372c368fe8ee0a49c/lib/rack/test.rb#L65), [action dispatch test #post](https://github.com/rails/rails/blob/1b9e85dbbd7d974143e67affb3166d7244cc99db/actionpack/lib/action_dispatch/testing/integration.rb#L37)
so for `Rack::Test` your third param can be smth like this:
```ruby
          env_request_headers = {
              'HTTP_ACCEPT' => 'application/json',
              'CONTENT_TYPE' => 'application/json'
          }
```
see how headers are prepared from `env` param [here](https://github.com/brynary/rack-test/blob/acdbee66fc765f15c2d3a1a372c368fe8ee0a49c/lib/rack/test.rb#L291)

if you use `Rack::Test` the better way to set headers is [`#header` method](https://github.com/brynary/rack-test/blob/acdbee66fc765f15c2d3a1a372c368fe8ee0a49c/lib/rack/test.rb#L135)

**Comment by jcavalieri** [comment]
Just tried this again. And it works fine as is. I'm not sure what happened. I'm assuming user error. However we did have some refactoring to consolidate our api, so likely the issue was somewhere in there. Dunno.

Closing this issue.
