### ISSUE TITLE
Doorkeeper Convert

### ISSUE THREAD

**Issue by maclover7** [intridea/grape#887]
Hi!

I am considering converting to Grape from Doorkeeper, but have one question. I know on Artsy they have the notion of a client_application and that is linked up to Grape for auth. Is there any guide on how to do this? My main application's auth engine is powered by Devise, if that helps at all.

**Comment by dblock** [comment]
I think you're comparing apples and oranges a bit. Grape itself doesn't do auth, and you can use Doorkeeper if you want with Grape, maybe not just out of the box. 

I had written http://code.dblock.org/2011/05/04/grape-api-authentication-w-devise.html a while ago, could be a start.

Please use the mailing list for questions.
