### ISSUE TITLE
Cloned InheritableSetting seems to clone unnecessary stuff

### ISSUE THREAD

**Issue by elado** [intridea/grape#891]
#739 creates a `point_in_time_copy` of route configuration. It `deep_dup`s everything in the hash, including classes. Problem is:

```ruby
desc "...", {
  entity: ArticlePresenter
}
```

The `ArticlePresenter` class is also getting `deep_dup`ed, which produces a `#<Class:0x...>` which leads to problems with equality and also not copying all class methods. It doesn't play nice with grape-swagger in some cases.

Currently I solved it by adding

```ruby
class Grape::Entity
  def self.deep_dup
    self
  end
end
```

I think I understand the need to make a current copy, but do you think it's OK to take out classes from the `deep_dup`?

**Comment by dblock** [comment]
Some of the dup'ing introduced in #739 was eventually removed, because we couldn't come up with a single failing test case. You should try with this one, too.

In theory, the not duping classes makes sense to me.

**Comment by elado** [comment]
I'm referring specifically to https://github.com/intridea/grape/blob/master/lib/grape/util/inheritable_setting.rb#L50
It uses ActiveSupport's clone and deep_dup. So to prepare a more efficient copy it needs to copy only instances, hashes, arrays etc.

`grape-swagger` for example, can show hundreds of `models` from all APIs, even when there are only a few unique.

What was the specific case to make a point in time copy?

**Comment by dblock** [comment]
I am not sure, @dspaeth-faber can speak to it. I think a lot of this was theoretical to avoid modifying a parent's namespace's settings down the nesting path.

**Comment by dspaeth-faber** [comment]
Well, it's not easy to explain, I think. You need point in time copies because values can change. 
This happens when configurations are made for a namespace.  Some thing like this:

```ruby

namespace :statuses do
  params do
    requires :user_id, type: Integer, desc: "A user ID."
  end
  namespace ":user_id" do
    desc "Retrieve a user's status."
    params do
      requires :status_id, type: Integer, desc: "A status ID."
    end
    get ":status_id" do
      User.find(params[:user_id]).statuses.find(params[:status_id])
    end
  end

 # now the inherited param should be user_name and not user_id
# to solf this you need point in time copies
  params do
     requires :user_name, type: String, desc: "A user name."
  end
  namespace ":user_name" do
     ... 
  end
end

```

I think there have been other examples too.
The approach to generate the config at "compile" time / when a class is loaded and evaluted
make things hard. A better way would be to create `Commands` and
replay them at need. But unfortunately at the moment I can't afford the time to do this change.

I apology.

**Comment by dblock** [comment]
Thanks @dspaeth-faber, no need to apologize :) Refactoring is hard, that change generally was really good for Grape's evolution and maturity, even though we have to fix issues as a fallout.

**Comment by dspaeth-faber** [comment]
The next evolution would be to create command-Objects instead of filling Hashes. This command chain can then be applied to Endpoints.

**Comment by dblock** [comment]
@toddmazierski Do you think https://github.com/intridea/grape/pull/1034 closes this?

**Comment by toddmazierski** [comment]
@dblock:

> Do you think #1034 closes this?

No, these settings appear to be handled with `InheritableValues`, whereas #1034 only touched `StackableValues`. I'm happy to create a new branch to drop `deep_dup` usage there, too, if recommended!

**Comment by dblock** [comment]
I think you should go for it @toddmazierski.
