### ISSUE TITLE
after specified API's serializers using format,the api.type requests are not found

### ISSUE THREAD

**Issue by TommyLike** [intridea/grape#914]
if i specified the API's serializers using format:  
```
format :json
```
the api will return 404 not found when called using api.type,such as:
```
/task/testcase.json
```
I found this issue in version 0.10.1 and it's ok in previous version

**Comment by dblock** [comment]
By previous version you mean 0.9.0, right?

This was introduced deliberately in https://github.com/intridea/grape/pull/809. We've discussed undoing that, I would still merge a PR.

**Comment by chaixl** [comment]
I also meet this problem after upgrading Grape,  #809  is a break change and big problem for me.

Before upgrading, I specified the API format:
```
format :json
```
I can access API by api and api.format_type
e.g.
```
/account/login
```
or
```
/account/login.json
```

After upgrading,  /account/login.json will return 404 not found. If remove "format :json", only  /account/login.json can be used.
access /account/login directly will return
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error>
<message>cannot convert String to xml</message>
</error>
```

But, out client use both /account/login and /account/login.json to access our API before.

**Comment by dblock** [comment]
You should be able to restore the old behavior by ensuring you have more than one format "supported", so after `format :json` add another content-type  via `content_type :foo, 'foo/bar'`. Let us know if that works. I am still looking for a PR for this.

**Comment by dblock** [comment]
The culprit is [here](https://github.com/intridea/grape/blob/master/lib/grape/path.rb#L24).

**Comment by dblock** [comment]
This has been reverted via https://github.com/intridea/grape/pull/1001, please test.
