### ISSUE TITLE
Allow blank not work when type Datetime

### ISSUE THREAD

**Issue by u2** [intridea/grape#915]
```
optional :remind_at, type: DateTime, allow_blank: true
```
When the params is `"remind_at"=>""`, grape return a message `to_do[remind_at] is invalid`.

**Comment by u2** [comment]
I am not sure this is justifiable or not.But it's very normal for me to 
```
requires :to_do, type: Hash do
  optional :remind_at, type: DateTime, allow_blank: true
end

to_do.update(params[:to_do])
```
If before to_do have a `remind_at`, then I want to clean it, How I can implement it.

And then what about Integer/Float, and so on?

**Comment by dblock** [comment]
I agree that DateTime, Integer and everything else should support `allow_blank`. Thanks for looking into this.

**Comment by u2** [comment]
Updated.Added `DateTime/Date/Numeric/Boolean` type support `allow_blank`.

**Comment by u2** [comment]
`allow_blank` default value is `true`?I think it should be clear in doc.

**Comment by dblock** [comment]
Yes, default values definitely need to be documented. Please.

**Comment by dblock** [comment]
This feature request was closed by https://github.com/intridea/grape/pull/916. Would welcome any future doc and whatever other updates. Thx.
