### ISSUE TITLE
Warning: toplevel constant DateTime referenced by Virtus::Attribute::DateTime

### ISSUE THREAD

**Issue by stgeneral** [intridea/grape#921]
Seems that recent pull request #916 introduces the warning:
```
.rvm/gems/ruby-2.1.2/bundler/gems/grape-5e48701fbbdb/lib/grape/validations/validators/coerce.rb:35: warning: toplevel constant DateTime referenced by Virtus::Attribute::DateTime
```

**Comment by dm1try** [comment]
This is right. We have `virtus >= 1.0.0` dependency.
There is no more `Virtus::Attribute::DateTime` in `virtus`, see -https://github.com/solnic/virtus/blob/v1.0.0/Changelog.md

> [BREAKING CHANGE] Integrated with axiom-types, most of the attribute sub-classes are gone (solnic)

so *Ruby constant lookup*, thank for the working code :smile:

**Comment by dm1try** [comment]
@u2 could you take a look?

**Comment by u2** [comment]
#925 
Thank you.It's my mistake.
