### ISSUE TITLE
How to bring parameters to new url when redirecting

### ISSUE THREAD

**Issue by calfzhou** [intridea/grape#922]
Document says that i could redirect to a new url using
```ruby
redirect '/statuses'
```

How can i pass api parameters to the new url?

**Comment by dm1try** [comment]
pls use [Grape Google Group](http://groups.google.com/group/ruby-grape) for questions.

> How can i pass api parameters to the new url?

You should pass params through the URL `redirect "/statuses?#{params.to_query}"`

**Comment by benjaminpenaolvera** [comment]
@dm1try and what is the output of this?

```
redirect "/statuses?#{params.to_query}" 
```
