### ISSUE TITLE
Log response body in after hook

### ISSUE THREAD

**Issue by BrandonMathis** [intridea/grape#923]
Hi! I want to setup some more verbose logging for grape. Part of that is logging the response body in an `after` hook but I am not sure how to get what would be the equivalent of `response.body`.

Basically, something like this
```
before do
  Rails.logger.debug "HEADERS: #{JSON.pretty_generate(headers)}"
  Rails.logger.debug "PARAMS: #{JSON.pretty_generate(params)}"
end

after do
  Rails.logger.debug "RESPONSE: #{JSON.pretty_generate(response.body)}"
end
```

Can anyone guide me where in the code I could get this response from or maybe just a gem that does this already super-chatty logging?

I don't want to re-invent the wheel.

grape 0.10.1
Using rails-api gem

**Comment by dblock** [comment]
Can you please post this to the mailing list? This has been [asked before](https://groups.google.com/forum/#!searchin/ruby-grape/logging). Thanks!

**Comment by BrandonMathis** [comment]
sry, thx for the link
