### ISSUE TITLE
Document how to test code coverage endpoint-by-endpoint

### ISSUE THREAD

**Issue by pragmaticivan** [intridea/grape#926]
I'm having some problems to track the coverage specs about the endpoints (request tests)

What's the best way to do that? Anyone is tracking this? and I think if yes it should be documented on README.

**Comment by dblock** [comment]
Can you talk about the problems you're having?

**Comment by pragmaticivan** [comment]
So, if you are using some gem to track the test coverage (ex: https://github.com/colszowka/simplecov)

It's hard to track if an endpoint is covered with tests.

I tried to force add the files and everything... but it's not working.

**Comment by michaelherold** [comment]
@pragmaticivan Are you setting up SimpleCov prior to loading your environment?

For example, if you are using RSpec

```ruby
# spec/spec_helper.rb
ENV['RACK_ENV'] ||= 'test'

require 'simplecov'
SimpleCov.start do
  add_filter 'spec'
end

require 'rack/test'

# Load your environment, i.e. the following with config/environment convention
require File.expand_path('../../config/environment', __FILE__)
```

Ensuring that you have Simplecov set up prior to loading your environment is probably what you need to do. Otherwise, could you show us how you're setting up your test suite?

**Comment by pragmaticivan** [comment]
Yes @michaelherold the problem is not withe the entire environment... is jut the covarage of grape files. I'm already using for models.

**Comment by michaelherold** [comment]
I guess I'm confused as to what your precise problem is.

Are you wonder how to write a test to test the functionality? I do that with Rack::Test following roughly the [guidelines in the README][guidelines]. Are you using Rack::Test, or are you trying some other method of making the actual calls to your API?

If you have those tests that make calls to your API and SimpleCov isn't showing any test coverage for your API, then the only hypothesis I can come up with is that your Grape environment is being loaded before SimpleCov.

Can you give a pared down example that illustrates your problem?

[guidelines]: https://github.com/intridea/grape#rspec

**Comment by pragmaticivan** [comment]
The problem was that I was invoking SimpleCov on `rails_spec` instead  `spec_helper`.

Sorry.
