### ISSUE TITLE
Requiring parameters for specific HTTP Request Type?

### ISSUE THREAD

**Issue by jaman1020** [intridea/grape#927]
I have a resource with typical RESTful URLs - get/put/delete on a 'object/:object_id' endpoint. I want to require certain parameters on just the 'PUT' endpoint (which is my edit route). 

Is it currently possible to do this? I've looked at namespaces and segmenting, but those add the name of the namespace to the URL, so creating an ':edit' segment makes the URL '/object/edit/:object_id', which I'd rather not do

If this isn't possible, maybe its worth a feature request?

**Comment by jaman1020** [comment]
Looking at it further, it looks like if you put a params do...end block right before the URL, it makes subsequent routes within that namespace require those params. This could hypothetically work, but you would have to keep the 'PUT' or other edit endpoint at the end of the current namespace. It also feels a bit hacky...

**Comment by dm1try** [comment]
We have a README :)

as you asked, here you have single RESTful URI for your `object` and three endpoints:
```ruby
namespace :object do
  route_param :id do
    get

    desc 'Edit profile'
    params do
      optional :name, type: String
    end
    put

    delete
  end
end
```

**Comment by jaman1020** [comment]
Yes I understand this now, but if you put the params block there, it will cause the 'delete' method to require the params as well, since it comes after the 'put' method. At least it does when I test it. 

Hence my second comment. It doesn't seem that putting a params block before a single route maps that params block to that single route, it maps to all subsequence routes as well.

**Comment by dm1try** [comment]
Hmm, interesting. I cannot repeat this behaviour using my example above. Could you please write a spec?

btw, which `grape` version is used? feel free to re-open.

**Comment by jaman1020** [comment]
Using grape 0.10.1
I'm not able to reproduce it either now, which is odd. Might have been some kind of weird caching issue or maybe just user error :P 
I'll re-open if I run into it again

**Comment by dblock** [comment]
This was a bug, #833, see https://github.com/intridea/grape/issues/833.
