### ISSUE TITLE
Idea: Provide constants for HTTP status codes

### ISSUE THREAD

**Issue by swistaczek** [intridea/grape#934]
Hi,
It would be nice if we could provide some kind of constants including HTTP status codes like Rails does ( http://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option ).

**Comment by dm1try** [comment]
`rack` already has smth similar, see [1](https://github.com/rack/rack/blob/e98a9f7ef0ddd9589145ea953948c73a8ce3caa9/test/spec_utils.rb#L413), [2](https://github.com/rack/rack/blob/aec5471cfbea791b72dd9a352514df5e50f10435/lib/rack/utils.rb#L580)

you can define a helper and use it easily
```ruby
helpers do
  def with_status(code, &block)
    status Rack::Utils.status_code(code)
    yield if block_given?
  end
end

get '/goodies' do
  with_status :payment_required do
    { error: 'give me some money' }
  end
end
```

**Comment by swistaczek** [comment]
@dm1try thanks for information :), what do you think to support this behaviour:
```status :method_not_allowed```

If method status detect that given argument is Symbol then it will try resolve correct HTTP code based on some rails-like symbol to http status code mapping table.

**Comment by dm1try** [comment]
`rails` [uses the same `rack` helper](https://github.com/rails/rails/blob/6d72485b6977804a872dcfa5d7ade2cec74c768e/actionpack/lib/action_dispatch/http/response.rb#L180) that I mentioned above.

If you are talking about "built-in sugar" for `#status` then I don't have any strong opinion because I don't use *named* statuses :)

**Comment by dblock** [comment]
I would be down with enabling this in Grape via `Rack::Utils.status_code(status)`.

**Comment by dabrorius** [comment]
Is somebody already working on this one? I would like to give it a shot.

**Comment by dblock** [comment]
@dabrorius Give it a shot!

**Comment by whatasunnyday** [comment]
@dblock Looks this issue can be closed.

**Comment by dblock** [comment]
Yep.
