### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by kevinhq** [intridea/grape#940]
I can run rake db:create, db:migrate, db:drop successfully. But when instantiating a user: User.new , it returns such error.

I used Postgresql adapter

Additionally, I have added this:
```ruby
use ActiveRecord::ConnectionAdapters::ConnectionManagement
```

to config.ru

**Comment by dblock** [comment]
Can you please bring this up on the mailing list, this doesn't have much to do with Grape.

**Comment by dblock** [comment]
Btw, there's a working project with Grape + ActiveRecord here: https://github.com/dblock/grape-with-roar/tree/with-activerecord
