### ISSUE TITLE
How to mock oauth authorization across all rspec examples?

### ISSUE THREAD

**Issue by ramarnat** [intridea/grape#941]
```
  # mock the response of the oauth-provider
  before(:each) do
    Grape::Endpoint.before_each do |endpoint|
      endpoint.stub(:authorize!).and_return(true)
    end
  end
```

causes this deprecation warning:
`Using rspec-mocks doubles or partial doubles outside the per-test lifecycle (such as in a before(:all) hook) is deprecated` 

This is using rspec-mocks `2.99.0`

After opening an issue https://github.com/rspec/rspec-mocks/issues/903 and feedback from @myronmarston It appears that the stub code runs when the app methods for get/put run. 

Now I am not sure if there is an easy way to stub the authorization, without adding ugly code to each example. 

Any ideas would be appreciated!

**Comment by dblock** [comment]
You should bring this type of things to the mailing list.

You can also delegate the method to a module, so instead of just `authorize!` do `AuthManager.authorize!` and then you can stub that.
