### ISSUE TITLE
RSpec regression tests

### ISSUE THREAD

**Issue by florrain** [intridea/grape#945]
Hey,

I was wondering what you would suggest to test the regression between a V2 and a V1 of an endpoint with RSpec?

I'd like for example to run the V1 specs on the V2 specs but just the ones which wasn't overridden in the V2.

I'd like to avoid duplicated tests just like it works with versioning in Grape.

Thanks!

**Comment by dblock** [comment]
Please use the [mailing list](http://groups.google.com/group/ruby-grape) for questions.

I would flag tests that are both v1 and v2 manually, something like `descibe 'reticulates splines', api: :v2 do ...` and run only the ones labeled accordingly. But maybe there's a way to do this better, I am sure someone will suggest something better on the list.
