### ISSUE TITLE
Feature request: support present_hash

### ISSUE THREAD

**Issue by u2** [intridea/grape#955]
My scenario is that we want to cache `present` like below:
```
result = cache(key: [entry.id, entry.updated_at], expires_in: 30.minutes) do
   present entry, with: Entities::Entry::Entry
end
result = Oj.load(result)
present result
present entry_user, Entities::Entry::DetailEntryUser
```
The result is only `entry_user`, grape do not support `present` a hash, just support `present key, value`, and I don't want to write something for traversing the result and `present` all the keys again.So what about adding support for `present_hash hash`.
I am sure it's reasonable or not, it's just a suggestion.If it's not reasonable, I will write some extend lib.

**Comment by dblock** [comment]
Before you begin, you should be able to `present` a Hash by extending Hash, no? I would try that first. 

Generally I think it's bad that you have an object half the time and a hash the other time through the same code. 

I would cache the whole thing and would check out [garner](https://github.com/artsy/garner) for your caching problems.

**Comment by u2** [comment]
Yes, it's not good that `present` an hash and then `present` an object.But, for some special scenario, like below
```
          to_dos_group = to_dos.group_by{|t| "#{t.end_at.year}-#{t.end_at.month}" if t.end_at }

          json = Jsonify::Builder.plain do |j|
            j.months(to_dos_group) do |group|
              category = group[0].to_s
              todos = group[1]
              j.year category.split('-')[0]
              j.month category.split('-')[1]
              j.count category.sum(&:left_number)
              j.to_dos(todos) do |todo|
                j.id todo.id
                j.title todo.title
                j.to_do_category_id todo.to_do_category_id
                j.to_do_category_name todo.to_do_category_name
                j.event_identifier todo.event_identifier
                j.description todo.description
                j.remind_at todo.remind_at.utc.iso8601 if todo.remind_at
                j.end_at todo.end_at.utc.iso8601 if todo.end_at
                j.expired todo.expired
              end
            end

            present Oj.load(json).merge(....)
```
We present a hash first, then we could not present a object, just can `merge` a hash.

Yes, garner[https://github.com/artsy/garner] is a good choice for caching the whole thing,but for the most time we want to cache fragment.

**Comment by dblock** [comment]
For the purpose of this proposal, do you agree that `present Hash` should work? I mean we don't want another method called `present_hash`. If you do, see whether it actually doesn't work already (there was some work on HEAD in that direction).

**Comment by u2** [comment]
Yes, I have read the README again.
>Grape supports a range of ways to present your data with some help from a generic present method, which accepts two arguments: the object to be presented and the options associated with it. The options hash may include :with, which defines the entity to expose.

But, any solution for this problem?Maybe I can write some extended lib.

**Comment by dblock** [comment]
I think your extension to allow `present <hash>` is reasonable. Unless I am missing something. Lets discuss it in the PR, I still have a few questions. Also if anyone else wants to pitch in that would be great.

**Comment by u2** [comment]
It's can be closed.
