### ISSUE TITLE
Multiple params validations in optional Array scope

### ISSUE THREAD

**Issue by durnoyabsurd** [intridea/grape#959]
Given the following specification:

```ruby
params do
  requires :id, type: Integer

  optional :smth, type: Array do
    optional :foo, type: Integer, default: 1
    optional :bar, type: Integer

    all_or_none_of :foo, :bar
  end
end
```

It will fail with `foo, bar provide all or none of parameters` for: `?id=123` request, although `smth` is optional.

**Comment by dblock** [comment]
That looks like a bug to me, care to build a test + maybe a fix?

**Comment by durnoyabsurd** [comment]
Updated the issue, actually the problem takes place only if default value is specified.
I'll try to fix it.

**Comment by dm1try** [comment]
This one already fixed in `master`

**Comment by durnoyabsurd** [comment]
Checked it on `master` – it's ok.
Thanks!
