### ISSUE TITLE
declared(params) not play well with rails strong parameters

### ISSUE THREAD

**Issue by anhhnguyen206** [intridea/grape#961]
It seems like that this PR #797 which make `declared(params)` return `Hashie::Mash` instead of native `Hash` causing issue with Rails strong parameter, as it causes `attributes.respond_to?(:permitted?) && !attributes.permitted?` alway return false, unless when the hash has key 'permitted'.

```ruby
     def sanitize_for_mass_assignment(attributes)
        if attributes.respond_to?(:permitted?) && !attributes.permitted?
          raise ActiveModel::ForbiddenAttributesError
        else
          attributes
        end
      end
```

Could we revert it back to normal Hash to make it play well with Rails?

Thanks, Anh Nguyen.

**Comment by dm1try** [comment]
@anhhnguyen206 see [hashie_rails](https://github.com/Maxim-Filimonov/hashie_rails)
