### ISSUE TITLE
Response format is not deeply included in modules

### ISSUE THREAD

**Issue by hodak** [intridea/grape#965]
Hi, I have two APIs defined: `api/main` and `api/admin`. I use `module Defaults` to include settings and helpers for both. It looks like this:

```ruby
module API
  module Defaults
    extend ActiveSupport::Concern
    included do
      format :json

      ...
    end
  end
end

module API
  module Main
    module Defaults
      extend ActiveSupport::Concern
      include API::Defaults

      included do
        ...
      end
    end
  end
end

module API
  module Main
    class Users < Grape::API
      include API::Main::Defaults
    end
  end
end
```

It worked well before updating `0.10.0` which closed https://github.com/intridea/grape/pull/809

My endpoints stopped working because no `format :json` was defined even though it includes module that defines the format. It starts working after defining `format :json` explicitly in `API::Main::Defaults` and `API::Main::Admin`.

Is this expected behavior?

**Comment by dblock** [comment]
I think this is a bug, but I am not 100% sure. It seems that you should be bringing in everything, including the format - you should write a test that reproduces it to start.

**Comment by hodak** [comment]
Hi, sorry for taking such a long time. I've created PR and explained it there: https://github.com/intridea/grape/pull/1001

**Comment by hodak** [comment]
Pull request has been merged, closing.
