### ISSUE TITLE
Error with passing array of hashes or array of arrays as params

### ISSUE THREAD

**Issue by petRUShka** [intridea/grape#966]
I have two different input

     let(:my_params) do
        {
            waypoints:{
             coordinates: [[55.542997, 37.540488] , [55.727232, 37.580328]]
            }
        }
      end

And 

      let(:my_params) do
        {
          waypoints: [{
            coordinates: [55.542997, 37.540488]
          },{
            coordinates: [55.727232, 37.580328]
          }]
        }
      end

In both cases I start a request using rack-test

      it "should return  something" do
        get "/api/url", my_params
      end

And when I try to access `params` i see something like this:
     
     {"waypoints"=>[{"coordinates"=>["55.542997", "37.540488", "55.727232", "37.580328"]}]}

instead of 

    {"waypoints"=>[{"coordinates"=>["55.542997", "37.540488"]}, 
                   {"coordinates"=>["55.727232", "37.580328"]}]}

**Comment by dm1try** [comment]
There is nothing related to`grape`. You are trying to use HTTP params with rich data structures and doing it wrong (I suggest using JSON if it's possible).

To clarify, see your example:
 ```ruby
    {
      waypoints: [{
        coordinates: [55.542997, 37.540488]
      },{
        coordinates: [55.727232, 37.580328]
      }]
    }
```
it turns into `?waypoints[][coordinates][]=55.542997&waypoints[][coordinates][]=37.540488&waypoints[][coordinates][]=55.727232&waypoints[][coordinates][]=37.580328` query string (there are no hashes or arrays in HTTP)

and result is expected
`{"waypoints"=>[{"coordinates"=>["55.542997", "37.540488", "55.727232", "37.580328"]}]}`

AFAIK there are no any specific RFC which has an information about how to send rich data structures using HTTP key/value pairs. But I think, you can rely on this one - http://www.w3.org/TR/html-json-forms/ (see example 5). So your params should be smth like this:
```ruby
    {
      waypoints: {
         "0" =>{
           coordinates: [55.542997, 37.540488]
         },
         "1" => {
           coordinates: [55.727232, 37.580328]
         }
      }
    }
```
and it should provide the result that you expected.

I'll close, feel free to re-open if you think it's related to `grape` :)
