### ISSUE TITLE
Error formatting

### ISSUE THREAD

**Issue by shiju-d** [intridea/grape#970]
Hi,
Is there any way to parse error response like this?
Say, { code: 'INVALID_REQ', message: 'Please submit required fields'  }
So far I could pass message key but not custom key 'code'. Please help.

Thanks.

**Comment by dblock** [comment]
I am not sure I understand. Parse where? With code? `JSON.parse(...)`?

Please bring up questions on the [google group](http://groups.google.com/group/ruby-grape).
