### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by shiju-d** [intridea/grape#971]
Hi,

Is there any way to log all exceptions in to our own custom logger file? Actually I have created my own logger and everything inherited from Grape::API seems to log properly. But exception log still writing to development.log file. Could you guys please suggest a method to achieve this?

**Comment by dblock** [comment]
You can create custom error handlers that use your own logger file, maybe as simple as adding a `rescue_from :all` with a log block? Or a middleware?

Please bring up questions on the [google group](http://groups.google.com/group/ruby-grape).
