### ISSUE TITLE
undefined method `error!' for #<Grape::Middleware::Error:0x007ffdfd9d3840>

### ISSUE THREAD

**Issue by TangMonk** [intridea/grape#982]
require 'grape-swagger'

```
module CarWash
  class Root < Grape::API
    rescue_from :all do |e|
      error!("rescued from #{e.class.name}")
    end
    mount V1::Api
  end
end
```

I want to catch all unexpected error.

But there is an error:

![image](https://cloud.githubusercontent.com/assets/3498786/7080978/4ea8137c-df6d-11e4-8c95-09e342b17b7f.png)

**Comment by dblock** [comment]
This hasn't shipped yet, was added in https://github.com/intridea/grape/pull/974.
