### ISSUE TITLE
config.filter_paremeters not working with Grape

### ISSUE THREAD

**Issue by blakeperdue** [intridea/grape#989]
Adding a filter to /config/initializers/filter_parameter_logging.rb is not working in Rails 4 with Grape v0.11.0

I have added a filter: `Rails.application.config.filter_parameters += [:password, :authentication_token]` but I'm still seeing `:authentication_token` in my logs:

```SELECT  `users`.* FROM `users` WHERE `users`.`authentication_token` = '$2a$10$ZTygoKxHQnQGeb4oWJyq283hdkHc2IOrxOgX9r0IXcE2JikptFIT.' LIMIT 1```

Any ideas how to get filtering working?

**Comment by dm1try** [comment]
I'll close. Related to https://github.com/intridea/grape/issues/556
