### ISSUE TITLE
Issues after grape upgradation

### ISSUE THREAD

**Issue by kavyavj** [intridea/grape#991]
When using grape(0.5.0) for the parameter type Integer got the validation error message "invalid parameter: 'parameter_name'" .But after upgrading to grape(0.11.0) this exception is not being caught.

Also with grape(0.11.0) the parameter with Type array is not displayed on the swagger.
parameter is defined like this:

params do
    requires :settings, :type => Array
end

**Comment by dblock** [comment]
This is a lot of Grape versions ago. I don't think I quite understand what you're trying to say here though, would you be so kind to bring this up on the mailing list with a more complete example, thanks!

**Comment by kavyavj** [comment]
When using grape(0.5.0) and grape (0.11.0) I get the below response when
the parameter plan_price_cents is passed as empty string.

1. With grape(0.5.0)

​

​
2.With grape (0.11.0)


​
With latest version of grape error message 'invalid parameter' is not
received.

**Comment by dblock** [comment]
@kavyavj Can you please email the list with details of the question, your code has been stripped above.
