### ISSUE TITLE
NoMethodError from active_support when using sample code

### ISSUE THREAD

**Issue by josh-** [intridea/grape#998]
I've also encountered the issue that [@funny-code](https://github.com/funny-code) mentioned in #327. @dblock asked them to open another issue to inspect it further but they don't appear to have done so.

In short, when using the sample code (my lightly-customised version that I reproduced this error with is available [here](https://gist.github.com/josh-/4a5e0157628db3ece436)), the following stack trace is shown when executing `rackup`:

    /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.1/lib/active_support/ordered_hash.rb:3:in `<top (required)>': undefined method `add_builtin_type' for Psych:Module (NoMethodError)
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/grape-0.10.1/lib/grape.rb:19:in `<top (required)>'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /Users/josh/Desktop/grape-issue/test.rb:1:in `<top (required)>'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/josh/Desktop/grape-issue/config.ru:1:in `block in <main>'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
        from /Users/josh/Desktop/grape-issue/config.ru:in `new'
        from /Users/josh/Desktop/grape-issue/config.ru:in `<main>'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:272:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:147:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/bin/rackup:4:in `<top (required)>'
        from /usr/bin/rackup:23:in `load'
        from /usr/bin/rackup:23:in `<main>'

I've found that the issue is resolved by adding `require 'yaml'` to the top of the `config.ru` file since the issue seems to be a dependancy issue with active_support trying to `add_builtin_type ` when used in grape.

**Comment by josh-** [comment]
I should also mention that I'm using grape with system ruby (ruby 2.0.0p481) on OS X 10.10.3. Thanks!

**Comment by dm1try** [comment]
In [your gist](https://gist.github.com/josh-/4a5e0157628db3ece436) you use `bundler` but you miss a `bundler/setup`configuration  - http://bundler.io/bundler_setup.html. You should fix it and re-check.

**Comment by dblock** [comment]
@dm1try is right on, closing, reopen if this doesn't resolve your problem

**Comment by josh-** [comment]
This resolves the problem – thanks so much!
