### ISSUE TITLE
referencing one API endpoint into another's API endpoint description

### ISSUE THREAD

**Issue by dan-corneanu** [intridea/grape#999]
Hello there,
I have two APIs like this:
* /api/v1/funds
* /api/v1/direct_debit

I would like to make a reference from the description attached to /api/v1/direct_debit to /api/v1/funds, something like this:

```
desc "Create a direct debit and schedule it. Direct debits will debit the account's investor bank account.\
          Information about investor's bank account can be obtained from the #{api_v1_investor_funds}"
```

and get back something like

```
desc "Create a direct debit and schedule it. Direct debits will debit the account's investor bank account.\
           Information about investor's bank account can be obtained from the /api/v1/funds"
```

Is there a way to achieve this?

**Comment by dm1try** [comment]
ATM it's not possible. See https://github.com/intridea/grape/pull/983

**Comment by dblock** [comment]
I am going to close this since #983 describes exactly this feature request.
